apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: company-api
  template:
    metadata:
      labels:
        app: company-api
    spec:
      containers:
        - name: company-api
          image: your-docker-repository/your-image-name:latest
          ports:
            - containerPort: 10005
